name: oxid package tests

on: [push]

jobs:
  stand_alone_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Validate composer.json
      run: composer validate   
    - name: validate php syntax
      run: find . -not -path "./vendor/*" -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    - name: validate bin php syntax
      run: php -l bin/oxid
    - name: install phpcs
      run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - name: phpcs psr12
      run: php phpcs.phar --standard=PSR12 --extensions=php --ignore=vendor .
#    - name: phplint, phpmd ...  
  tests:
    needs: stand_alone_checks
    strategy:
      matrix:
        tag: [v3_6.1_php7.1, v3_6.1_php7.2, v3_6.2-rc_php7.2, v3_6.2-rc_php7.1, v3_dev-master_php7.2]         
    runs-on: ubuntu-latest
    container:
      image: oxidprojects/oxid-test:${{matrix.tag}}
      options: -v /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    env:
      MODULE_NAME: modulesconfig
      DB_HOST: "localhost;unix_socket=/var/run/mysqld/mysqld.sock"
    steps:
    - uses: actions/checkout@v1
    - name: setup oxid
      run: bash /var/www/oxideshop/scripts/setupOxid.sh
    - name: install this package into oxid
      run: bash /var/www/oxideshop/scripts/setupPackage.sh
    - name: phpstan loose
      continue-on-error: true
      run: |
        MD=$(pwd)
        cd /var/www/oxid/
        touch autoload.oxid.php
        composer remove phpstan/phpstan-strict-rules --dev
        vendor/bin/phpstan analys  --level 2 --configuration phpstan.neon $MD
    - name: psalm
      run: |
        MD=$(pwd)
        cd /var/www/oxid
        curl -OL https://circleci.com/api/v1.1/project/github/weirdan/psalm/232/artifacts/0/home/docker/project/build/psalm.phar
        php psalm.phar --stats --show-info=true $MD
    - name: run console 
      run: |
        cd /var/www/oxid/
        vendor/bin/oxid list
    - name: install module internals
      run: |
        cd /var/www/oxid
        composer require "oxid-community/moduleinternals:dev-master"
        vendor/bin/oxid list
    - name: run module internals
        vendor/bin/oxid module:activate moduleinternals
        vendor/bin/oxid list
        vendor/bin/oxid fix:states -a
        ls -al source/log
    - name: done
      if: failure()
      run: |
        cd /var/www/oxideshop
        ls -al source/log
        cat source/log/*
        
